export const RECEIVE_TEAM = 'RECEIVE_TEAM'
export const CREATE_LINEUP = 'CREATE_LINEUP'
export const SET_INNING = 'SET_INNING'
export const ADD_PLAYER = 'ADD_PLAYER'
export const ADD_LINEUP = 'ADD_LINEUP'

export const RECEIVE_GAMES = 'RECEIVE_GAMES'
export const ADD_PATHS_HOME = 'ADD_PATHS_HOME'
export const ADD_PATHS_AWAY = 'ADD_PATHS_AWAY'
export const ADD_ROSTERS = 'ADD_ROSTERS'
export const SELECT_GAME = 'SELECT_GAME'
export const SELECT_TEAM = 'SELECT_TEAM'
